# define formats
formats:
  simple: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {extra[logger_name]} | {file: <16} | {function} : {line} - {message}"
  console: " <green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <red>{extra[logger_name]}</red> | <cyan>{file: <16} | {function}</cyan> : {line} - <white>{message}</white>"

# define handlers
handlers:
  handler_file:
    sink: "./.logs"
    format: "simple"
    level: "DEBUG"
    # retention: "30 days"
    # rotation: "1 day"
    # compression: "zip"
    # serialize: true
  handler_console:
    sink: "sys.stdout"
    format: "console"
    level: "DEBUG"

# define logging tasks
loggers:
  default_task:
    - handler: "handler_file"
      level: "DEBUG"
    - handler: "handler_console"
      level: "DEBUG"