# =================================================
# LOGGER MANAGEMENT
# =================================================
# define formats
formats:
  simple: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {extra[logger_name]} | {file: <16} | {function} : {line} - {message}"
  console: " <green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <red>{extra[logger_name]}</red> | <cyan>{file: <16} | {function}</cyan> : {line} - <white>{message}</white>"

# define handlers
handlers:
  handler_file:
    sink: "./logs/test.log"
    format: "simple"
    level: "DEBUG"
    # retention: "30 days"
    # rotation: "1 day"
    # compression: "zip"
    # serialize: true
  handler_console:
    sink: "sys.stdout"
    format: "console"
    level: "DEBUG"

# define logging tasks
loggers:
  logger_a:
    - handler: "handler_file"
      level: "WARNING"
    - handler: "handler_console"
      level: "DEBUG"
  logger_b:
    - handler: "handler_console"
      level: "INFO"
# =================================================
# COPY MANAGEMENT
# =================================================
# define retry settings for copy operations
retry:
  max_attempts: 3   # optional. Default if left empty is 2.
  wait: 3           # optional. Default if left empty is 1. Wait time between retries in seconds.

# define copy tasks
copy_manager:
  test_copy_1: #copy_name
    path_patterns: "./logs/**"
    copy_destination: "./logs_copy_1/"
    root_dir: "./logs/"
    copy_interval: 5 # seconds
    create_dest_dirs: true
    preserve_structure: true
  test_copy_2:
    path_patterns: "./logs/test.log"
    copy_destination: "./logs_copy_2/"
    # root dir:
    copy_interval: 5
    create_dest_dirs: true
    preserve_structure: false
